import uuid
from datetime import date as _date, datetime, timezone
from decimal import Decimal
from typing import Optional

from sqlalchemy import Date, DateTime, ForeignKey, Numeric, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base

# Status values for a notification row.
NOTIFICATION_STATUSES = ("unread", "read", "dismissed")
# Alert triggers fired as a bill approaches its due date.
ALERT_TYPES = ("7_DAYS", "3_DAYS", "1_DAY", "DUE_DATE")
# Which entity the alert points at — polymorphic `target_id` (no FK).
TARGET_TYPES = ("transaction", "bill", "recurring")


class Notification(Base):
    """A due-date alert for a bill ("conta a pagar") or credit-card invoice.

    Generated by the hourly Celery task scanning scheduled transactions,
    real credit-card bills and recurring projections. The row carries a
    display snapshot (description, amount, account name…) so the read path
    never has to join against entities that may later be edited/deleted.

    Deduplication: exactly one alert per (user, target, alert_type, due
    date cycle) — a second run of the job is a no-op thanks to
    ``uq_notifications_target_alert_cycle``.
    """

    __tablename__ = "notifications"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("workspaces.id", ondelete="CASCADE"), index=True
    )
    account_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("accounts.id", ondelete="CASCADE"), index=True, nullable=False
    )
    target_type: Mapped[str] = mapped_column(String(20), nullable=False)
    target_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    alert_type: Mapped[str] = mapped_column(String(20), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="unread")
    # Display snapshot (denormalized on purpose — see class docstring).
    description: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    amount: Mapped[Optional[Decimal]] = mapped_column(Numeric(precision=15, scale=2), nullable=True)
    currency: Mapped[Optional[str]] = mapped_column(String(3), nullable=True)
    type: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    account_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    due_date: Mapped[_date] = mapped_column(Date, nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    sent_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=True
    )

    __table_args__ = (
        UniqueConstraint(
            "user_id", "target_type", "target_id", "alert_type", "due_date",
            name="uq_notifications_target_alert_cycle",
        ),
    )
