"""Due-date alert generation and notification CRUD.

The hourly Celery task calls ``generate_due_date_alerts`` per user. It scans
three sources for bills whose due date is about to hit:

* ``transaction`` — scheduled ("a pagar") transactions, using ``due_date``
  (falling back to ``date`` for generated placeholders that never stored one);
* ``bill`` — real credit-card invoices (``credit_card_bills``);
* ``recurring`` — projected occurrences of active recurring transactions that
  are not yet materialized (same math the dashboard uses).

Alerts fire only on the trigger days (7 / 3 / 1 / 0 before the due date) and
are deduplicated by ``(user, target, alert_type, due_date)``, so the job is
idempotent no matter how often it runs.
"""
import uuid
from datetime import date, datetime, timedelta
from zoneinfo import ZoneInfo

from sqlalchemy import delete, or_, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.account import Account
from app.models.category import Category
from app.models.credit_card_bill import CreditCardBill
from app.models.notification import Notification
from app.models.recurring_transaction import RecurringTransaction
from app.models.transaction import Transaction
from app.models.user import User
from app.services.recurring_transaction_service import get_occurrences_in_range

# Trigger day (days before due) -> alert type. Only these days fire.
ALERT_DAYS: dict[int, str] = {7: "7_DAYS", 3: "3_DAYS", 1: "1_DAY", 0: "DUE_DATE"}
# Inclusive window of due dates we consider on each run.
WINDOW_DAYS = 7


def _user_today(user: User) -> date:
    """The user's local "today" based on their timezone preference."""
    tz = (user.preferences or {}).get("timezone") or "UTC"
    try:
        return datetime.now(ZoneInfo(tz)).date()
    except Exception:
        return date.today()


async def _excluded_category_ids(session: AsyncSession, user_id: uuid.UUID) -> set[uuid.UUID]:
    """Category ids that must not generate alerts (transfers / ignored)."""
    result = await session.execute(
        select(Category.id).where(
            Category.user_id == user_id,
            or_(
                Category.treat_as_transfer.is_(True),
                Category.is_ignored.is_(True),
            ),
        )
    )
    return {row[0] for row in result.all()}


async def _account_names(session: AsyncSession, user_id: uuid.UUID) -> dict[uuid.UUID, str]:
    result = await session.execute(
        select(Account.id, Account.display_name, Account.name).where(
            Account.user_id == user_id
        )
    )
    return {row[0]: (row[1] or row[2]) for row in result.all()}


async def _scheduled_tx_candidates(
    session: AsyncSession,
    user_id: uuid.UUID,
    today: date,
    window_end: date,
) -> list[Transaction]:
    """Scheduled transactions due within the window. Uses ``due_date`` when
    present, falling back to ``date`` for placeholders generated by
    ``generate_pending`` (which never stores ``due_date``)."""
    result = await session.execute(
        select(Transaction).where(
            Transaction.user_id == user_id,
            Transaction.status == "scheduled",
            or_(
                Transaction.due_date.between(today, window_end),
                # placeholder rows: due_date is null, date is the vencimento
                Transaction.due_date.is_(None) & Transaction.date.between(today, window_end),
            ),
        )
    )
    return list(result.scalars().all())


async def _bill_candidates(
    session: AsyncSession, user_id: uuid.UUID, today: date, window_end: date
) -> list[CreditCardBill]:
    result = await session.execute(
        select(CreditCardBill).where(
            CreditCardBill.user_id == user_id,
            CreditCardBill.due_date.between(today, window_end),
        )
    )
    return list(result.scalars().all())


async def _recurring_candidates(
    session: AsyncSession,
    user_id: uuid.UUID,
    today: date,
    window_end: date,
) -> list[tuple[RecurringTransaction, list[date]]]:
    """Active recurrings with projected occurrences inside the window that are
    not yet materialized as a linked transaction (mirrors generate_pending's
    existing-placeholder check, so a projected alert doesn't duplicate the
    one produced from the materialized scheduled transaction)."""
    result = await session.execute(
        select(RecurringTransaction).where(
            RecurringTransaction.user_id == user_id,
            RecurringTransaction.is_active.is_(True),
            RecurringTransaction.account_id.is_not(None),
        )
    )
    recs = list(result.scalars().all())

    candidates: list[tuple[RecurringTransaction, list[date]]] = []
    for rec in recs:
        occurrences = get_occurrences_in_range(
            start=rec.next_occurrence,
            frequency=rec.frequency,
            end_date=rec.end_date,
            range_start=today,
            range_end=window_end + timedelta(days=1),  # exclusive end → includes today+7
            intended_day=rec.day_of_month or rec.start_date.day,
        )
        if not occurrences:
            continue
        placeholders = (
            await session.execute(
                select(Transaction.id, Transaction.date).where(
                    Transaction.recurring_transaction_id == rec.id,
                    Transaction.date.in_(occurrences),
                )
            )
        ).all()
        materialized_dates = {row[1] for row in placeholders}
        pending = [occ for occ in occurrences if occ not in materialized_dates]
        if pending:
            candidates.append((rec, pending))
    return candidates


async def _dismiss_stale_alerts(session: AsyncSession, user_id: uuid.UUID) -> int:
    """Alerts whose underlying entity is gone or no longer relevant (a
    scheduled transaction got paid/deleted, a bill was removed, a recurring
    was deactivated) are auto-dismissed so the bell doesn't nag forever."""
    active = ("unread", "read")
    total = 0

    async def _dismiss_type_ids(target_type: str, alive_ids: set[uuid.UUID]) -> int:
        result = await session.execute(
            select(Notification.id, Notification.target_id).where(
                Notification.user_id == user_id,
                Notification.target_type == target_type,
                Notification.status.in_(active),
            )
        )
        rows = result.all()
        stale = [alert_id for alert_id, target_id in rows if target_id not in alive_ids]
        if not stale:
            return 0
        result = await session.execute(
            update(Notification)
            .where(Notification.id.in_(stale))
            .values(status="dismissed")
        )
        return result.rowcount or 0

    # transaction alerts → alive if the tx is still scheduled
    result = await session.execute(
        select(Notification.target_id).where(
            Notification.user_id == user_id,
            Notification.target_type == "transaction",
            Notification.status.in_(active),
        )
    )
    tx_target_ids = [row[0] for row in result.all()]
    if tx_target_ids:
        alive = set(
            (
                await session.execute(
                    select(Transaction.id).where(
                        Transaction.id.in_(tx_target_ids),
                        Transaction.status == "scheduled",
                    )
                )
            ).scalars().all()
        )
        total += await _dismiss_type_ids("transaction", alive)

    # bill alerts → alive if the bill row still exists
    result = await session.execute(
        select(Notification.target_id).where(
            Notification.user_id == user_id,
            Notification.target_type == "bill",
            Notification.status.in_(active),
        )
    )
    bill_target_ids = [row[0] for row in result.all()]
    if bill_target_ids:
        alive = set(
            (
                await session.execute(
                    select(CreditCardBill.id).where(
                        CreditCardBill.id.in_(bill_target_ids)
                    )
                )
            ).scalars().all()
        )
        total += await _dismiss_type_ids("bill", alive)

    # recurring alerts → alive if the recurring is still active
    result = await session.execute(
        select(Notification.target_id).where(
            Notification.user_id == user_id,
            Notification.target_type == "recurring",
            Notification.status.in_(active),
        )
    )
    rec_target_ids = [row[0] for row in result.all()]
    if rec_target_ids:
        alive = set(
            (
                await session.execute(
                    select(RecurringTransaction.id).where(
                        RecurringTransaction.id.in_(rec_target_ids),
                        RecurringTransaction.is_active.is_(True),
                    )
                )
            ).scalars().all()
        )
        total += await _dismiss_type_ids("recurring", alive)

    await session.commit()
    return total


def _build_alerts(
    user: User,
    today: date,
    txs: list[Transaction],
    bills: list[CreditCardBill],
    recs: list[tuple[RecurringTransaction, list[date]]],
    accounts: dict[uuid.UUID, str],
    excluded_categories: set[uuid.UUID],
) -> list[dict]:
    alerts: list[dict] = []
    now = datetime.now(ZoneInfo("UTC"))

    for tx in txs:
        if tx.category_id in excluded_categories:
            continue
        due = tx.due_date or tx.date
        days_left = (due - today).days
        alert_type = ALERT_DAYS.get(days_left)
        if not alert_type:
            continue
        alerts.append(
            {
                "user_id": user.id,
                "workspace_id": tx.workspace_id,
                "account_id": tx.account_id,
                "target_type": "transaction",
                "target_id": tx.id,
                "alert_type": alert_type,
                "status": "unread",
                "description": tx.description,
                "amount": tx.amount,
                "currency": tx.currency,
                "type": tx.type,
                "account_name": accounts.get(tx.account_id),
                "due_date": due,
                "created_at": now,
                "sent_at": now,
            }
        )

    for bill in bills:
        days_left = (bill.due_date - today).days
        alert_type = ALERT_DAYS.get(days_left)
        if not alert_type:
            continue
        account_name = accounts.get(bill.account_id)
        alerts.append(
            {
                "user_id": user.id,
                "workspace_id": bill.workspace_id,
                "account_id": bill.account_id,
                "target_type": "bill",
                "target_id": bill.id,
                "alert_type": alert_type,
                "status": "unread",
                "description": f"Fatura · {account_name}" if account_name else "Fatura",
                "amount": bill.total_amount,
                "currency": bill.currency,
                "type": "debit",
                "account_name": account_name,
                "due_date": bill.due_date,
                "created_at": now,
                "sent_at": now,
            }
        )

    for rec, occurrences in recs:
        if rec.category_id in excluded_categories:
            continue
        for occ in occurrences:
            days_left = (occ - today).days
            alert_type = ALERT_DAYS.get(days_left)
            if not alert_type:
                continue
            alerts.append(
                {
                    "user_id": user.id,
                    "workspace_id": rec.workspace_id,
                    "account_id": rec.account_id,
                    "target_type": "recurring",
                    "target_id": rec.id,
                    "alert_type": alert_type,
                    "status": "unread",
                    "description": rec.description,
                    "amount": rec.amount,
                    "currency": rec.currency,
                    "type": rec.type,
                    "account_name": accounts.get(rec.account_id),
                    "due_date": occ,
                    "created_at": now,
                    "sent_at": now,
                }
            )

    return alerts


async def create_due_date_alerts(
    session: AsyncSession, user: User
) -> list["Notification"]:
    """Scan all due sources for ``user`` and insert any alerts that fired.

    Idempotent: duplicate (user, target, alert_type, due_date) rows are
    skipped. Returns the newly-created ``Notification`` rows (committed) so
    callers can trigger push delivery for them.
    """
    today = _user_today(user)
    window_end = today + timedelta(days=WINDOW_DAYS)

    await _dismiss_stale_alerts(session, user.id)

    txs = await _scheduled_tx_candidates(session, user.id, today, window_end)
    bills = await _bill_candidates(session, user.id, today, window_end)
    recs = await _recurring_candidates(session, user.id, today, window_end)

    if not txs and not bills and not recs:
        return []

    accounts = await _account_names(session, user.id)
    excluded = await _excluded_category_ids(session, user.id)

    alerts = _build_alerts(user, today, txs, bills, recs, accounts, excluded)
    if not alerts:
        return []

    # Dedup (idempotency): skip keys already present for this user within the
    # same due-date window. The DB unique constraint remains the safety net.
    existing_rows = (
        await session.execute(
            select(
                Notification.target_type,
                Notification.target_id,
                Notification.alert_type,
                Notification.due_date,
            ).where(
                Notification.user_id == user.id,
                Notification.due_date.between(today, window_end),
            )
        )
    ).all()
    existing = {
        (row[0], row[1], row[2], row[3]) for row in existing_rows
    }

    new_alerts = [
        a
        for a in alerts
        if (a["target_type"], a["target_id"], a["alert_type"], a["due_date"]) not in existing
    ]
    if not new_alerts:
        return []

    created = [Notification(**a) for a in new_alerts]
    session.add_all(created)
    await session.commit()
    return created


async def generate_due_date_alerts(session: AsyncSession, user: User) -> int:
    """Count-only variant of ``create_due_date_alerts`` (compat)."""
    return len(await create_due_date_alerts(session, user))


async def get_notifications(
    session: AsyncSession,
    workspace_id: uuid.UUID,
    status: str | None = None,
) -> list[Notification]:
    """Active notifications (unread + read) for the workspace, unread first.
    Pass ``status`` to narrow to a single value (e.g. ``"dismissed"``); without
    it, dismissed rows are hidden."""
    query = select(Notification).where(Notification.workspace_id == workspace_id)
    if status:
        query = query.where(Notification.status == status)
    else:
        query = query.where(Notification.status != "dismissed")
    query = query.order_by(
        Notification.status == "unread",
        Notification.created_at.desc(),
    )
    result = await session.execute(query)
    return list(result.scalars().all())


async def unread_count(session: AsyncSession, workspace_id: uuid.UUID) -> int:
    result = await session.execute(
        select(Notification.id).where(
            Notification.workspace_id == workspace_id,
            Notification.status == "unread",
        )
    )
    return len(result.all())


async def get_notification(
    session: AsyncSession, notification_id: uuid.UUID, workspace_id: uuid.UUID
) -> Notification | None:
    result = await session.execute(
        select(Notification).where(
            Notification.id == notification_id,
            Notification.workspace_id == workspace_id,
        )
    )
    return result.scalar_one_or_none()


async def mark_read(
    session: AsyncSession, notification_id: uuid.UUID, workspace_id: uuid.UUID
) -> bool:
    result = await session.execute(
        update(Notification)
        .where(
            Notification.id == notification_id,
            Notification.workspace_id == workspace_id,
            Notification.status == "unread",
        )
        .values(status="read")
    )
    await session.commit()
    return (result.rowcount or 0) > 0


async def mark_dismissed(
    session: AsyncSession, notification_id: uuid.UUID, workspace_id: uuid.UUID
) -> bool:
    result = await session.execute(
        update(Notification)
        .where(
            Notification.id == notification_id,
            Notification.workspace_id == workspace_id,
        )
        .values(status="dismissed")
    )
    await session.commit()
    return (result.rowcount or 0) > 0


async def mark_all_read(session: AsyncSession, workspace_id: uuid.UUID) -> int:
    result = await session.execute(
        update(Notification)
        .where(
            Notification.workspace_id == workspace_id,
            Notification.status == "unread",
        )
        .values(status="read")
    )
    await session.commit()
    return result.rowcount or 0


async def delete_notifications(
    session: AsyncSession, workspace_id: uuid.UUID, user_id: uuid.UUID
) -> None:
    """Remove a user's notifications for a workspace (used by workspace leave)."""
    await session.execute(
        delete(Notification).where(
            Notification.workspace_id == workspace_id,
            Notification.user_id == user_id,
        )
    )
    await session.commit()
