apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "talisma.fullname" . }}-config
  labels:
    {{- include "talisma.labels" . | nindent 4 }}
data:
  FRONTEND_URL: {{ include "talisma.frontendUrl" . | quote }}
  PLUGGY_OAUTH_REDIRECT_URI: {{ default (include "talisma.oauthRedirectUri" .) .Values.config.pluggyOauthRedirectUri | quote }}
  ENABLE_BANKING_OAUTH_REDIRECT_URI: {{ default (include "talisma.oauthRedirectUri" .) .Values.config.enableBankingOauthRedirectUri | quote }}
  {{- range $key, $value := .Values.config }}
  {{- if and (ne $key "pluggyOauthRedirectUri") (ne $key "enableBankingOauthRedirectUri") }}
  {{ $key | snakecase | upper }}: {{ tpl (print $value) $ | quote }}
  {{- end }}
  {{- end }}
